TELEGRAM_ACCESS_TOKEN = 'Telegram bot API key goes here'
TELEGRAM_CHANNEL_ID = 'The channel or group ID where you want to upload images'
REDDIT_APP_KEY = 'Reddit App Key'
REDDIT_APP_SECRET = 'Reddit App Secret'
REDDIT_USER_AGENT = 'Reddit App User Agent'
